# Generated by Django 3.2.12 on 2022-03-23 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20220322_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Пусто'), (1, 'Ненависть'), (2, 'Неприязнь'), (3, 'Нейтрально'), (4, 'Обожание'), (5, 'Любовь')], default=0, help_text='От 1 до 5', validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
