# Generated by Django 3.2.12 on 2022-04-04 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0013_auto_20220404_1504'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0003_alter_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating',
                                    to='catalog.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
