# Generated by Django 3.2.12 on 2022-03-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='second_name',
            field=models.TextField(default='empty'),
        ),
    ]
