# Generated by Django 3.2.12 on 2022-03-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_second_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='second_name',
        ),
        migrations.AddField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
