# Generated by Django 3.2.12 on 2022-03-22 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220322_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(help_text='Макс 200 символов', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9-_]+', message='Только латиница, цифры и символы - и _')], verbose_name='Тэг'),
        ),
    ]
