# Generated by Django 3.2.12 on 2022-03-22 19:13

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20220322_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='tags', to='catalog.Tag'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Макс 200 символов', max_length=200, null=True, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Макс 150 символов', max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Минимум 2 слова', null=True, validators=[catalog.validators.validate_brilliant, catalog.validators.validate_2_words], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Макс 200 символов', max_length=200, null=True, unique=True, verbose_name='Тег'),
        ),
    ]
