# Generated by Django 3.2.12 on 2022-03-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20220322_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='catalog.Tag'),
        ),
    ]
