# Generated by Django 3.2.12 on 2022-03-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20220323_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Макс 200 символов', max_length=200, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Макс 200 символов', max_length=200, null=True, unique=True, verbose_name='Название'),
        ),
    ]
