# Generated by Django 3.2.12 on 2022-04-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0012_auto_20220323_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Макс 150 символов', max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Макс 150 символов', max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='items', to='catalog.Tag', verbose_name='Теги'),
        ),
    ]
