# Generated by Django 3.2.12 on 2022-04-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0013_auto_20220404_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Макс 200 символов', max_length=200, null=True, unique=True,
                                   verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Макс 200 символов', max_length=200, null=True, unique=True,
                                   verbose_name='Slug'),
        ),
    ]
