# Generated by Django 3.2.12 on 2022-04-15 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0014_auto_20220405_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-weight',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
